@section('content')

    <div class="well widget row-fluid">

        {{ Former::horizontal_open()->rules([
        	'title' => 'required',
        	'short_title' => 'required',
            'url' => 'required',
        	'icon' => 'required',
        ]) }}

        {{ Former::text('title', 'Título')->class('span12') }}
        {{ Former::text('short_title', 'Título Curto')->class('span12') }}
        {{ Former::text('url', 'URL (link do grupo)')->class('span12') }}
        {{ Former::select('icon', 'Ícone')
        ->addOption(null)
        ->options(array(
        'entypo-note' => 'note',
        'entypo-beamed-note' => 'beamed-note',
        'entypo-music' => 'music',
        'entypo-search' => 'search',
        'entypo-flashlight' => 'flashlight',
        'entypo-mail' => 'mail',
        'entypo-heart' => 'heart',
        'entypo-heart-empty' => 'heart-empty',
        'entypo-star' => 'star',
        'entypo-star-empty' => 'star-empty',
        'entypo-user' => 'user',
        'entypo-users' => 'users',
        'entypo-add-user' => 'add-user',
        'entypo-video' => 'video',
        'entypo-picture' => 'picture',
        'entypo-camera' => 'camera',
        'entypo-layout' => 'layout',
        'entypo-check' => 'check',
        'entypo-plus' => 'plus',
        'entypo-circled-plus' => 'circled-plus',
        'entypo-squared-plus' => 'squared-plus',
        'entypo-minus' => 'minus',
        'entypo-circled-minus' => 'circled-minus',
        'entypo-squared-minus' => 'squared-minus',
        'entypo-help' => 'help',
        'entypo-circled-help' => 'circled-help',
        'entypo-info' => 'info',
        'entypo-circled-info' => 'circled-info',
        'entypo-back' => 'back',
        'entypo-home' => 'home',
        'entypo-link' => 'link',
        'entypo-attach' => 'attach',
        'entypo-lock' => 'lock',
        'entypo-lock-open' => 'lock-open',
        'entypo-eye' => 'eye',
        'entypo-tag' => 'tag',
        'entypo-bookmark' => 'bookmark',
        'entypo-bookmarks' => 'bookmarks',
        'entypo-flag' => 'flag',
        'entypo-thumbs-up' => 'thumbs-up',
        'entypo-thumbs-down' => 'thumbs-down',
        'entypo-download' => 'download',
        'entypo-upload' => 'upload',
        'entypo-save' => 'save',
        'entypo-upload-cloud' => 'upload-cloud',
        'entypo-reply' => 'reply',
        'entypo-reply-all' => 'reply-all',
        'entypo-forward' => 'forward',
        'entypo-quote' => 'quote',
        'entypo-code' => 'code',
        'entypo-export' => 'export',
        'entypo-pencil' => 'pencil',
        'entypo-feather' => 'feather',
        'entypo-print' => 'print',
        'entypo-retweet' => 'retweet',
        'entypo-keyboard' => 'keyboard',
        'entypo-comment' => 'comment',
        'entypo-chat' => 'chat',
        'entypo-bell' => 'bell',
        'entypo-warning' => 'warning',
        'entypo-vcard' => 'vcard',
        'entypo-address' => 'address',
        'entypo-location' => 'location',
        'entypo-map' => 'map',
        'entypo-direction' => 'direction',
        'entypo-compass' => 'compass',
        'entypo-cup' => 'cup',
        'entypo-trash' => 'trash',
        'entypo-doc' => 'doc',
        'entypo-docs' => 'docs',
        'entypo-landscape-doc' => 'landscape-doc',
        'entypo-text-doc' => 'text-doc',
        'entypo-text-doc-inverted' => 'text-doc-inverted',
        'entypo-newspaper' => 'newspaper',
        'entypo-open-book' => 'open-book',
        'entypo-book' => 'book',
        'entypo-folder' => 'folder',
        'entypo-archive' => 'archive',
        'entypo-box' => 'box',
        'entypo-rss' => 'rss',
        'entypo-phone' => 'phone',
        'entypo-cog' => 'cog',
        'entypo-tools' => 'tools',
        'entypo-share' => 'share',
        'entypo-shareable' => 'shareable',
        'entypo-bag' => 'bag',
        'entypo-calendar' => 'calendar',
        'entypo-login' => 'login',
        'entypo-logout' => 'logout',
        'entypo-mic' => 'mic',
        'entypo-mute' => 'mute',
        'entypo-sound' => 'sound',
        'entypo-volume' => 'volume',
        'entypo-clock' => 'clock',
        'entypo-hourglass' => 'hourglass',
        'entypo-light-down' => 'light-down',
        'entypo-light-up' => 'light-up',
        'entypo-adjust' => 'adjust',
        'entypo-block' => 'block',
        'entypo-resize-full' => 'resize-full',
        'entypo-resize-small' => 'resize-small',
        'entypo-popup' => 'popup',
        'entypo-publish' => 'publish',
        'entypo-arrow-combo' => 'arrow-combo',
        'entypo-circled-down' => 'circled-down',
        'entypo-circled-left' => 'circled-left',
        'entypo-circled-right' => 'circled-right',
        'entypo-circled-up' => 'circled-up',
        'entypo-down' => 'down',
        'entypo-left' => 'left',
        'entypo-right' => 'right',
        'entypo-up' => 'up',
        'entypo-down-bold' => 'down-bold',
        'entypo-left-bold' => 'left-bold',
        'entypo-right-bold' => 'right-bold',
        'entypo-up-bold' => 'up-bold',
        'entypo-down-thin' => 'down-thin',
        'entypo-left-thin' => 'left-thin',
        'entypo-right-thin' => 'right-thin',
        'entypo-up-thin' => 'up-thin',
        'entypo-ccw' => 'ccw',
        'entypo-cw' => 'cw',
        'entypo-level-down' => 'level-down',
        'entypo-level-up' => 'level-up',
        'entypo-shuffle' => 'shuffle',
        'entypo-loop' => 'loop',
        'entypo-switch' => 'switch',
        'entypo-play' => 'play',
        'entypo-stop' => 'stop',
        'entypo-record' => 'record',
        'entypo-to-end' => 'to-end',
        'entypo-to-start' => 'to-start',
        'entypo-progress-0' => 'progress-0',
        'entypo-progress-1' => 'progress-1',
        'entypo-progress-2' => 'progress-2',
        'entypo-progress-3' => 'progress-3',
        'entypo-palette' => 'palette',
        'entypo-list' => 'list',
        'entypo-add-to-list' => 'add-to-list',
        'entypo-signal' => 'signal',
        'entypo-trophy' => 'trophy',
        'entypo-battery' => 'battery',
        'entypo-back-in-time' => 'back-in-time',
        'entypo-monitor' => 'monitor',
        'entypo-mobile' => 'mobile',
        'entypo-network' => 'network',
        'entypo-cd' => 'cd',
        'entypo-inbox' => 'inbox',
        'entypo-install' => 'install',
        'entypo-globe' => 'globe',
        'entypo-cloud' => 'cloud',
        'entypo-thunder-cloud' => 'thunder-cloud',
        'entypo-flash' => 'flash',
        'entypo-moon' => 'moon',
        'entypo-paper-plane' => 'paper-plane',
        'entypo-leaf' => 'leaf',
        'entypo-lifebuoy' => 'lifebuoy',
        'entypo-mouse' => 'mouse',
        'entypo-briefcase' => 'briefcase',
        'entypo-suitcase' => 'suitcase',
        'entypo-dot' => 'dot',
        'entypo-two-dots' => 'two-dots',
        'entypo-three-dots' => 'three-dots',
        'entypo-brush' => 'brush',
        'entypo-magnet' => 'magnet',
        'entypo-infinity' => 'infinity',
        'entypo-erase' => 'erase',
        'entypo-pie-chart' => 'pie-chart',
        'entypo-line-graph' => 'line-graph',
        'entypo-bar-graph' => 'bar-graph',
        'entypo-area-graph' => 'area-graph',
        'entypo-graduation-cap' => 'graduation-cap',
        'entypo-language' => 'language',
        'entypo-ticket' => 'ticket',
        'entypo-water' => 'water',
        'entypo-droplet' => 'droplet',
        'entypo-air' => 'air',
        'entypo-credit-card' => 'credit-card',
        'entypo-clipboard' => 'clipboard',
        'entypo-megaphone' => 'megaphone',
        'entypo-database' => 'database',
        'entypo-drive' => 'drive',
        'entypo-bucket' => 'bucket',
        'entypo-thermometer' => 'thermometer',
        'entypo-key' => 'key',
        'entypo-flow-cascade' => 'flow-cascade',
        'entypo-flow-branch' => 'flow-branch',
        'entypo-flow-tree' => 'flow-tree',
        'entypo-flow-line' => 'flow-line',
        'entypo-flow-parallel' => 'flow-parallel',
        'entypo-rocket' => 'rocket',
        'entypo-gauge' => 'gauge',
        'entypo-traffic-cone' => 'traffic-cone',
        'entypo-cc' => 'cc',
        'entypo-cc-by' => 'cc-by',
        'entypo-cc-nc' => 'cc-nc',
        'entypo-cc-nc-eu' => 'cc-nc-eu',
        'entypo-cc-nc-jp' => 'cc-nc-jp',
        'entypo-cc-sa' => 'cc-sa',
        'entypo-cc-nd' => 'cc-nd',
        'entypo-cc-pd' => 'cc-pd',
        'entypo-cc-zero' => 'cc-zero',
        'entypo-cc-share' => 'cc-share',
        'entypo-cc-remix' => 'cc-remix',
        'entypo-sweden' => 'sweden',
        'entypo-db-shape' => 'db-shape',
        'entypo-db-logo' => 'db-logo',
        ))
        ->data_placeholder('Selecione um Ícone')
        ->class('span12 select2')
        }}

        {{ Former::actions()
          ->primary_submit('Salvar')
          ->inverse_reset('Limpar') }}

        {{ Former::close() }}

    </div>

@stop
